image:
  - Visual Studio 2015

configuration:
  - Debug

branches:
  only:
    - master

platform:
  - x86
  - x64

install:
  # Install ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version

before_build:
  - if "%platform%" == "x86" (call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat")
  - if "%platform%" == "x64" (call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64)
  - cd C:\projects\sqlite3cpp

build_script:
  - mkdir build
  - cd build
  - cmake .. -G Ninja
  - ninja
  - ninja test
